apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        - name: app
          image: gcr.io/your-gcp-project-id/sales-app:latest # <-- Replace with your image path
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            # The app connects to the proxy on localhost
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"

        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.9
          command:
            - "/cloud_sql_proxy"
            - "-instances=$(CLOUDSQL_INSTANCE_CONNECTION_NAME)=tcp:5432"
          securityContext:
            runAsNonRoot: true
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"