apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  GKE_REGION: "us-central1"
  CLOUDSQL_INSTANCE_CONNECTION_NAME: "your-gcp-project-id:us-central1:your-instance-id-us"
  # You can override other values here if needed, for example, if you have a different Spanner instance for the US
  SPANNER_INSTANCE_ID: "your-spanner-instance-id-us"